//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Germane1.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAppointmentsInfo
    {
        public int appointmentid { get; set; }
        public int userid { get; set; }
        public System.DateTime appointment_CreationDate { get; set; }
        public System.DateTime appointment_Date { get; set; }
        public string appointment_Title { get; set; }
        public string appointment_Description { get; set; }
        public System.TimeSpan appointment_Time { get; set; }
    }
}
